### ISSUE TITLE
README.md has TODO for chart repository and name

### ISSUE THREAD

**Issue by CapKenR** [octarinesec/octarine-operator#117]
The README.md for both the operator and agent charts doesn't specify the URL of the chart repository or the chart name to use. It looks like they're still on someone's TODO list.

```
helm repo add vmware TODO-chart-repo/TODO-chart-name
helm repo update
helm install cbcontainers-operator TODO-chart-repo/TODO-chart-name
```
```
helm repo add vmware TODO-chart-repo/TODO-chart-name -f values.yaml
helm repo update
helm install cbcontainers-agent TODO-chart-repo/TODO-chart-name -f values.yaml
```

**Comment by ltsonov-cb** [comment]
Thank you for reporting this.
We have decided to only support installation from source for the time being. Closed since #163  also removed this section of the docs.
