### ISSUE TITLE
Changes for agentNamespace have multiple errors

### ISSUE THREAD

**Issue by CapKenR** [octarinesec/octarine-operator#139]
The changes made to add the agentNamespace value have multiple errors.

In charts/cbcontainers-agent/cbcontainers-agent-chart/templates/rbac.yaml:

`  namespace: { { default "cbcontainers-dataplane" .Values.agentNamespace } }`

should be:

`  namespace: {{ default "cbcontainers-dataplane" .Values.agentNamespace }}`

in 3 places.

The same error occurs twice in charts/cbcontainers-agent/cbcontainers-agent-chart/templates/service-accounts.yaml.

And, in charts/cbcontainers-agent/cbcontainers-agent-chart/templates/containers-agent.yaml the `  namespace: {{ default "cbcontainers-dataplane" .Values.agentNamespace }}` should be under `metadata` not `spec`.

**Comment by CapKenR** [comment]
I see @asankov-cb 's pull request, [More customisation for the charts](https://github.com/octarinesec/octarine-operator/pull/128), has the first two problems fixed but not the third.

**Comment by CapKenR** [comment]
Here are three helm install dry runs that show the errors.
```bash
❯ helm install cbcontainers-agent ./cbcontainers-agent-chart -f test-values.yaml --dry-run
Error: INSTALLATION FAILED: YAML parse error on cbcontainers-agent/templates/rbac.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{"default \"cbcontainers-dataplane\" .Values.agentNamespace":interface {}(nil)}
```
```bash
❯ helm install cbcontainers-agent ./cbcontainers-agent-chart -f test-values.yaml --dry-run
Error: INSTALLATION FAILED: YAML parse error on cbcontainers-agent/templates/service-accounts.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{"default \"cbcontainers-dataplane\" .Values.agentNamespace":interface {}(nil)}
```
```bash
❯ helm install cbcontainers-agent ./cbcontainers-agent-chart -f test-values.yaml --dry-run
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(CBContainersAgent.spec): unknown field "namespace" in io.carbonblack.containers.operator.v1.CBContainersAgent.spec
```

**Comment by asankov-cb** [comment]
> And, in charts/cbcontainers-agent/cbcontainers-agent-chart/templates/containers-agent.yaml the   namespace: {{ default "cbcontainers-dataplane" .Values.agentNamespace }} should be under metadata not spec.

@CapKenR the reason that this field is under `spec`, not `metadata` is because the CR is not namespace-scoped, so the `namespace` field is not for the CR itself, but for the resources that are configured by the CR.

Maybe as a compromise we might keep it under `spec` but change it to something like `resourceNamespace` so that it's more clear that it's not for the CR itself, but for the resources. WDYT @BenRub @CapKenR ?
