### ISSUE TITLE
Helm install fails due to missing "octarine-dataplane" namespace

### ISSUE THREAD

**Issue by sgriffith3** [octarinesec/octarine-operator#31]
When trying to install the helm chart as described in the README.md file, I was unable to do so and got this error:

```
Error: create: failed to create: namespaces "octarine-dataplane" not found
```

Please update the documentation to include the step to create this namespace prior to installing the helm chart, or update the chart to include the creation of this namespace. 

```
kubectl create namespace octarine-dataplane
```

**Comment by asankov-cb** [comment]
We have added to ability to customize whether Helm should create the namespace or not. See https://github.com/octarinesec/octarine-operator/tree/main/charts/cbcontainers-operator#namespace

I think we can close this now, feel free to re-open/open another issue if the problem persists.
