### ISSUE TITLE
operator-v3.0.1.1 - CustomResourceDefinitions not working as expected

### ISSUE THREAD

**Issue by EvoilaDemolab** [octarinesec/octarine-operator#54]
Hi CB Team, 
We are currently trying to secure our on premise kubernetes clusters using the CB Containers Suite. 
Our Kubernetes Cluster runs in Debian 10 and kubernetes v1.22.1.
The Installation processes showed errors on pretty much all of the CustomResourceDefinitions.
According to the CB Dashboard the cluster is healthy and registered correctly, but the images are not being scanned. 
I suspect this is due to the the CB components deployed to the k8s cluster not being able to operate correctly since the CRDs are not present and the CB kinds are not recognized.
How can we proceed to make this work?

History of the CB installation below:

controlplane@debian-k8s-controlplane:~/cbmanifests$ wget https://setup.containers.carbonblack.io/operator-v3.0.1
--2021-09-10 13:29:19--  https://setup.containers.carbonblack.io/operator-v3.0.1
Resolving setup.containers.carbonblack.io (setup.containers.carbonblack.io)... 13.32.14.31, 13.32.14.40, 13.32.14.84, ...
Connecting to setup.containers.carbonblack.io (setup.containers.carbonblack.io)|13.32.14.31|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 18341 (18K) [binary/octet-stream]
Saving to: 'operator-v3.0.1.1'

operator-v3.0.1.1       100%[==============================>]  17.91K  --.-KB/s    in 0.002s  

2021-09-10 13:29:20 (9.01 MB/s) - 'operator-v3.0.1.1' saved [18341/18341]
controlplane@debian-k8s-controlplane:~/cbmanifests$ k apply -f operator-v3.0.1.1 
namespace/cbcontainers-dataplane created
serviceaccount/cbcontainers-operator created
role.rbac.authorization.k8s.io/cbcontainers-leader-election-role created
clusterrole.rbac.authorization.k8s.io/cbcontainers-manager-role created
rolebinding.rbac.authorization.k8s.io/cbcontainers-leader-election-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/cbcontainers-manager-rolebinding created
configmap/cbcontainers-manager-config created
secret/cbcontainers-operator-public-registry-secret created
deployment.apps/cbcontainers-operator created
unable to recognize "operator-v3.0.1.1": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "operator-v3.0.1.1": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
controlplane@debian-k8s-controlplane:~/cbmanifests$ kubectl create secret generic cbcontainers-access-token --namespace cbcontainers-dataplane --from-literal=accessToken=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
secret/cbcontainers-access-token created
controlplane@debian-k8s-controlplane:~/cbmanifests$ wget https://setup.containers.carbonblack.io/cr-ccf8d6ac-5ca1-48bd-a7c0-342e141b7902
--2021-09-10 14:04:59--  https://setup.containers.carbonblack.io/cr-ccf8d6ac-5ca1-48bd-a7c0-342e141b7902
Resolving setup.containers.carbonblack.io (setup.containers.carbonblack.io)... 13.32.14.84, 13.32.14.124, 13.32.14.31, ...
Connecting to setup.containers.carbonblack.io (setup.containers.carbonblack.io)|13.32.14.84|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 790 [binary/octet-stream]
Saving to: 'cr-ccf8d6ac-5ca1-48bd-a7c0-342e141b7902'

cr-ccf8d6ac-5ca1-48bd-a 100%[==============================>]     790  --.-KB/s    in 0s      

2021-09-10 14:05:00 (18.4 MB/s) - 'cr-ccf8d6ac-5ca1-48bd-a7c0-342e141b7902' saved [790/790]

controlplane@debian-k8s-controlplane:~/cbmanifests$ kubectl apply -f https://setup.containers.carbonblack.io/cr-ccf8d6ac-5ca1-48bd-a7c0-342e141b7902
unable to recognize "https://setup.containers.carbonblack.io/cr-ccf8d6ac-5ca1-48bd-a7c0-342e141b7902": no matches for kind "CBContainersCluster" in version "operator.containers.carbonblack.io/v1"
unable to recognize "https://setup.containers.carbonblack.io/cr-ccf8d6ac-5ca1-48bd-a7c0-342e141b7902": no matches for kind "CBContainersHardening" in version "operator.containers.carbonblack.io/v1"
unable to recognize "https://setup.containers.carbonblack.io/cr-ccf8d6ac-5ca1-48bd-a7c0-342e141b7902": no matches for kind "CBContainersRuntime" in version "operator.containers.carbonblack.io/v1"

**Comment by BenRub** [comment]
Hello @EvoilaDemolab.
According to the logs you have provided,
it seems like an old issue of using CRD version v1beta1 which is deleted starting from Kubernetes v1.22.

This issue is fixed by installing the latest operator with the bash script we provide in the documentation:
https://github.com/octarinesec/octarine-operator#from-script
You can also use the setup wizard from our dashboard.

The bash scripts checks the k8s version and applies the proper operator components (including the right CRD versions).

If you prefer to not use the bash script, here are the specs you can apply in your cluster in order to install the latest operator.
https://setup.containers.carbonblack.io/operator-v4.0.0
https://setup.containers.carbonblack.io/operator-v4.0.0-kubernetes-under-1-16

In your case, (k8s version 1.22.1), you will need to use the first one.

Feel free to send any question you have.
Ben.

**Comment by EvoilaDemolab** [comment]
Hi Ben, 

I did the second version and installed the operator-v4.0.0 from scratch and deleted the old deployment. 
Looks like everything works as expected. Thank you and best regards!
